---
title: "Análisis Intermedio de Covid19 en Costa Rica"
author: "Fiorella Cordero"
date: '2022-05-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Entradas**
## Datos generales de casos
```{r}
covid_nacional <- read.csv(file = "C:/Users/Fiorela/Downloads/05_24_22_CSV_GENERAL.csv", sep = ";")
```
## Paquetes
```{r}
library(ggplot2)  
library(plotly)  
library(readr)  
library(dplyr) 
library(DT)
```


# **Procesamiento**
## Opciones generales
```{r}
options(scipen = 7)
```
## Curación de Datos
```{r}
covid_nacional$FECHA <- as.Date(covid_nacional$FECHA, format = "%d/%m/%Y")
```


# Salidas

## Datos nacionales
#### Importación de datos nacionales de covid-19
```{r}
covid_nacional <-
  read_delim(
    file = 'C:/Users/Fiorela/Downloads/05_24_22_CSV_GENERAL.csv',
    delim = ";",
    col_select = c("FECHA", "positivos", "fallecidos", "RECUPERADOS", "activos")
  )

```
#### Transformación
```{r}
covid_nacional <-
  covid_nacional %>%
  select(
    fecha = FECHA,
    positivos = positivos,
    fallecidos = fallecidos,
    recuperados = RECUPERADOS,
    activos = activos
  ) %>% 
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y"))
```

### Tabla
```{r}
covid_nacional %>%
  datatable(options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
```


### Gráfico de líneas



## Datos cantonales

### Tabla

### Gráfico de líneas
